create table if not exists store
(
    id   bigint generated by default as identity
        primary key,
    created_at  timestamp(6) with time zone,
    created_by  varchar(255),
    is_deleted  boolean,
    modified_at timestamp(6) with time zone,
    modified_by varchar(255),
    version     integer,
    code        varchar(50)      not null
        constraint ix_unique_store_code
            unique,
    latitude    double precision not null,
    longitude   double precision not null,
    name        varchar(150)     not null
);

create index if not exists ix_store_latitude_longitude
    on store (latitude, longitude);

create index if not exists ix_store_latitude
    on store (latitude);

create index if not exists ix_store_longitude
    on store (longitude);



create table if not exists courier
(
    id              bigint generated by default as identity
        primary key,
    created_at      timestamp(6) with time zone,
    created_by      varchar(255),
    is_deleted      boolean,
    modified_at     timestamp(6) with time zone,
    modified_by     varchar(255),
    version         integer,
    identity_number varchar(11)  not null
        constraint ix_unique_identitynumber
            unique,
    name            varchar(100) not null
);

create index if not exists ix_courier_identitynumber
    on courier (identity_number);
